---
- hosts: all
  connection: ssh

  tasks:
    - name: install java
      command: amazon-linux-extras install java-opendjk11 -y

...
##################################

---
- hosts: all
  connection: ssh

  tasks:
    - name: all in one
      yum: name=git state=present

...
########################################################
---
- hosts: all
  connection: ssh

  tasks:
    - name: install httpd
      yum: name=httpd state=present


    - name: started the httpd
      service: name=httpd state=started

...
##########################################
---
- hosts: dev
  connection: ssh
                                                   ##file create
  tasks:
    - name: all in one
      file:
        path: "myfolder" 
        state: touch

---
- hosts: dev
  connection: ssh
  
  tasks:
    - name: all in one                          ###########folder create
      file:
        path: "myfolder" 
        state: directory
...
##################################################
---
- hosts: dev
  connection: ssh

  tasks:
    - name: all in one                 ########permissiona change
      file:
        path: "cloud/aws"
        mode: 777
...
        
        
