---
- hosts: localhost

  tasks:
    - name: install the java
      command: yum install java-17-amazon-corretto -y

    - name: get url from jenkinsion
      get_url:
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
        dest: "/etc/yum.repos.d/jenkins.repo"

    - name: get passworg
      ansible.builtin.rpm_key:
        key: "https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"
        state: present

    - name: install jenkins
      yum: name=jenkins state=present

    - name: start jenkins
      service: name=jenkins state=started
