---
- hosts: test
  connection: ssh

  vars:
    web: httpd
    scm: git

    tasks:
      - name: this is varibles
        yum: name={{web}} state=present

      - name: this is second
        yum: name={{git}} state=present

...

####################################looooooppppppppssssss#############

---
- hosts: test
  connection: ssh

  tasks:
    - name: multi files
      file: path={{item}} state=touch   ########################
      with_items:
        - f2
        - f4
        - f5

    tasks:
   - name: loops conecpt
     user: name={{item}} state=present
     with_items:
       - guru
       - aws
       - cloud
       - devops
tasks:
   - name: loops conececpt with file
     group: name={{item}} state=present
     with_items:
       - guru
       - aws
       - cloud
       - devops
...
